---
name: Live test

on:
  pull_request:

jobs:
  live-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install core dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
        run: poetry install

      - name: Live type check
        run: poetry run mypy tests/test_mypy_output.py | poetry run mypy-gh-action-report
